<?php
// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the sum of the
// even-valued terms.

$m = 1;
$n = 2;
$sum = $n;
$FOUR_MILLION = 4000000;

while (true) {
  $next = $m + $n;
  if ($next > $FOUR_MILLION) {
    break;
  }

  if ($next % 2 === 0) {
    $sum += $next;
  }

  $m = $n;
  $n = $next;
}
print "Sum: $sum\n";
